version: ~> 1.0

os: linux
language: cpp

branches:
  only:
    - qtwave

git:
  depth: 1

env:
  global:
    - GTKWAVE_NUM_JOBS=$(echo `nproc` + 1 | bc)

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" != "windows" ]; then
      sudo apt-get install libgtk2.0-dev libgtk-3-dev gperf
    fi

script:
  - |
    cd gtkwave3-gtk3
    ./configure
    make -j $GTKWAVE_NUM_JOBS

